/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Whole;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEEKdRevZ0lk0= >>
// ----------- >>

/**
* Coeur de l'application, doit avant tou lancer COnnectionUniqueBD
*/

// ----------- << class.annotations@AAAAAAGEEKdRevZ0lk0= >>
// ----------- >>
public class Controlleur {
    // ----------- << attribute.annotations@AAAAAAGEIHa8b/dPHI8= >>
    // ----------- >>
    private Connection bd;

    /**
    * Permet de sauvegarder des métadonnés (ou autre) dans le but d'un copier coller
    */

    // ----------- << attribute.annotations@AAAAAAGEIIIlXMkTv6I= >>
    // ----------- >>
    private Object pressePapier;

    private Connection getBd() {
        return bd;
    }

    private Object getPressePapier() {
        return pressePapier;
    }

    private void setBd(Connection bd) {
        this.bd = bd;
    }

    private void setPressePapier(Object pressePapier) {
        this.pressePapier = pressePapier;
    }

    /**
    * @param String name 
    * @param String pwd
    */

    // ----------- << method.annotations@AAAAAAGELrr87wPx3E0= >>
    // ----------- >>
    public Boolean Login(void String name, void String pwd) {
    // ----------- << method.body@AAAAAAGELrr87wPx3E0= >>
    // ----------- >>
    }
    /**
    * @param String name 
    * @param String pwd 
    * @param String confirm
    */

    // ----------- << method.annotations@AAAAAAGELsui0MkWVxw= >>
    // ----------- >>
    public Boolean AddUser(void String name, void String pwd, void String confirm) {
    // ----------- << method.body@AAAAAAGELsui0MkWVxw= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGEEKdRevZ0lk0= >>
// ----------- >>
}