/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package whole.exportPackage;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEzpXcBdick5I= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEzpXcBdick5I= >>
// ----------- >>
public interface ExportTypeInterface {
    // ----------- << method.annotations@AAAAAAGEzpbIUAevq+k= >>
    // ----------- >>
    void export();
// ----------- << interface.extras@AAAAAAGEzpXcBdick5I= >>
// ----------- >>
}