/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Whole.ccmsPackage;

import Whole.daoPackage.AbstractDAO;
import Whole.Metadonnee;

import java.awt.image.BufferedImage;
import java.util.*;

/**
 * Classe représentant les lettrines
 */
public class Lettrine implements CCMS {

    private Ouvrage ouvrage;

    /**
     * Liste des métadonnées associées à la lettrine
     * @see Whole.Metadonnee
     */
    private ArrayList<Metadonnee> metadonnees;

    /**
     * numéro de la page sur laquelle figure la lettrine
     */
    private int nbPage;

    /**
     * id de la lettrine dans la base
     */
    private int id;

    /**
     * Liste des tags associés à la lettrine
     */
    private ArrayList<Tag> tags;

    /**
     * Constructeur de la classe Lettrine
     * @param ouvrage Ouvrage
     * @param metadonnees ArrayList<Metadonnee>
     * @param nbPage int
     * @param id int
     * @param tags ArrayList<Tag>
     */
    public Lettrine(Ouvrage ouvrage, ArrayList<Metadonnee> metadonnees, int nbPage, int id, ArrayList<Tag> tags) {
        this.ouvrage = ouvrage;
        this.metadonnees = metadonnees;
        this.nbPage = nbPage;
        this.id = id;
        this.tags = tags;
    }
    /**
     * Constructeur à utiliser pour les instances de changement
     */
    public Lettrine(){
        this.ouvrage = null;
        this.metadonnees = null;
        this.nbPage = -2;
        this.id = -2;
    }
    /**
     * Renvoie un objet de type Ouvrage
     * @return ouvrage
     */
    public Ouvrage getOuvrage() {
        return ouvrage;
    }

    /**
     * Renvoie la liste des métadonnées associées à la lettrine
     * @return ArrayList<Metadonnees> liste des métadonnées associés
     * @see Metadonnee
     */
    public ArrayList<Metadonnee> getMetadonnees() {
        return metadonnees;
    }

    /**
     * Renvoie le numéro de la page sur laquelle la lettrine figure.
     * @return nbPage
     */
    public int getNbPage() {
        return nbPage;
    }

    /**
     * Renvoie l'id de la lettrine dans la base de données
     * @return id
     */
    public int getId() {
        return id;
    }

    /**
     * Renvoie la liste des tags associés à la lettrine
     * @return tags
     */
    public ArrayList<Tag> getTags() {
        return tags;
    }

    /**
     * permet de modifier la valeur de l'ouvrage par l'objet en paramètre
     * @param ouvrage Ouvrage : nouvelle valeur de ouvrage
     */
    public void setOuvrage(Ouvrage ouvrage) {
        this.ouvrage = ouvrage;
    }

    /**
     * permet de modifier la valeur du numéro de la page par l'objet en paramètre
     * @param nbPage int : nouvelle valeur de nbPage
     */
    public void setNbPage(int nbPage) {
        this.nbPage = nbPage;
    }

    /**
     * Remplace la valeur actuelle de metadonnees par la valeur passée en paramètre
     * @param metadonnees : ArrayList de métadonnées qui vient remplacer la valeur actuelle
     */
    public void setMetadonnees(ArrayList<Metadonnee> metadonnees) {
        this.metadonnees = metadonnees;
    }


    public void setId(int id) {
        this.id = id;
    }

    public void setTags(ArrayList<Tag> tags) {
        this.tags = tags;
    }

    /**
     * Cette methode permet d'ajouter la métadonnée passée en paramètre à la lettrine.
     * Elle affecte la liste de métadonnées metadonnees en y ajoutant la métadonnée passée en paramètre.
     * @param meta Metadonnee : metadonnée à ajouter
     * @see Metadonnee
     */
    public void AjouterMetadonnees(Metadonnee meta) {

    }

    /**
     * Cette méthode permet de supprimer la métadonnée passée en paramètre à la lettrine.
     * Elle affecte la liste de métadonnées metadonnees en en retirant la métadonnée passée en paramètre.
     * @param meta : métadonnée à supprimer
     * @see Metadonnee
     */
    public void SupprimerMetadonnees(Metadonnee meta) {

    }


    /**
     * Modifie un CCMS, appel une méthode d'un objet de type AbstractDAO
     *
     * @see AbstractDAO
     */
    @Override
    public void modifier() {

    }

    /**
     * Cherche un CCMS, appel une méthode d'un objet de type AbstractDAO
     *
     * @see AbstractDAO
     */
    @Override
    public void chercher() {

    }

    /**
     * Créer un CCMS, appel une méthode d'un objet de type AbstractDAO
     *
     * @see AbstractDAO
     */
    @Override
    public void creer() {

    }

    /**
     * Supprime un CCMS, appel une méthode d'un objet de type AbstractDAO
     *
     * @see AbstractDAO
     */
    @Override
    public void supprimer() {

    }

    /**
     * Renvoie l'image d'une lettrine sur un serveur distant, si non-trouvable alors envoyé image par défaut
     * @return L'image issue du lien
     * @see BufferedImage
     */
    public BufferedImage loadImage(){
        return null;
    }
}