/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Whole.ccmsPackage;

import Whole.Metadonnee;

import java.util.*;

/**
 * Classe représentant les lettrines
 */
public class Lettrine implements CCMS<Lettrine> {
    /**
     * L'ouvrage dans lequel se trouve la lettrine
     */
    private Ouvrage ouvrage;

    /**
     * Liste des métadonnées associées à la lettrine
     * @see Whole.Metadonnee
     */
    private ArrayList<Metadonnee> metadonnees;

    /**
     * numéro de la page sur laquelle figure la lettrine
     */
    private int nbPage;

    /**
     * id de la lettrine dans la base
     */
    private int id;

    /**
     * Liste des tags associés à la lettrine
     */
    private ArrayList<Tag> tags;
    /**
     * Le lien web de la lettrine
     */
    private String lien;

    /**
     * Constructeur de la classe Lettrine
     * @param ouvrage Ouvrage
     * @param metadonnees ArrayList<Metadonnee>
     * @param nbPage int
     * @param id int
     * @param tags ArrayList<Tag>
     */
    public Lettrine(Ouvrage ouvrage, ArrayList<Metadonnee> metadonnees, int nbPage, int id, ArrayList<Tag> tags, String lien) {
        this.ouvrage = ouvrage;
        this.metadonnees = metadonnees;
        this.nbPage = nbPage;
        this.id = id;
        this.tags = tags;
        this.lien = lien;
    }
    /**
     * Constructeur à utiliser pour les instances de changement
     */
    public Lettrine(){
        this.ouvrage = null;
        this.metadonnees = null;
        this.nbPage = -2;
        this.id = -2;
        this.lien = null;
    }
    /**
     * Renvoie un objet de type Ouvrage
     * @return ouvrage
     */
    public Ouvrage getOuvrage() {
        return ouvrage;
    }

    /**
     * Renvoie la liste des métadonnées associées à la lettrine
     * @return ArrayList<Metadonnees> liste des métadonnées associés
     * @see Metadonnee
     */
    public ArrayList<Metadonnee> getMetadonnees() {
        return metadonnees;
    }

    /**
     * Renvoie le numéro de la page sur laquelle la lettrine figure. Si le numero de page de la lettrine
     * est inconue : return -1
     * @return nbPage
     */
    public int getNbPage() {
        return nbPage;
    }

    /**
     * Renvoie l'id de la lettrine dans la base de données
     * @return id
     */
    public int getId() {
        return id;
    }

    /**
     * Renvoie la liste des tags associés à la lettrine
     * @return tags
     */
    public ArrayList<Tag> getTags() {
        return tags;
    }

    /**
     * renvoie le lien de la métadonnée
     * @return lien String : lien  de la métadonnée
     */
    public String getLien() {
        return lien;
    }

    /**
     * permet de modifier la valeur de l'ouvrage par l'objet en paramètre
     * @param ouvrage Ouvrage : nouvelle valeur de ouvrage
     */
    public void setOuvrage(Ouvrage ouvrage) {
        this.ouvrage = ouvrage;
    }

    /**
     * permet de modifier la valeur du numéro de la page par l'objet en paramètre
     * @param nbPage int : nouvelle valeur de nbPage. Si on ne connait pas le numéro de la page sur
     *                     laquelle la lettrine figure, nbPage = -1
     */
    public void setNbPage(int nbPage) {
        this.nbPage = nbPage;
    }


    /**
     * Remplace la valeur actuelle de metadonnees par la valeur passée en paramètre
     * @param metadonnees : ArrayList de métadonnées qui vient remplacer la valeur actuelle
     */
    public void setMetadonnees(ArrayList<Metadonnee> metadonnees) {
        this.metadonnees = new ArrayList<>();
        for(Metadonnee meta : metadonnees){
            this.metadonnees.add(meta);
        }
    }

    /**
     * Change la valeur de l'id
     * @param id Le nouvel identifiant de la lettrine
     */
    public void setId(int id) {
        this.id = id;
    }

    public void setTags(ArrayList<Tag> tags) {
        this.tags = new ArrayList<>();
        for(Tag tag : tags){
            this.tags.add(tag);
        }
    }

    public void setLien(String lien) {
        this.lien = lien;
    }

    /**
     * Cette methode permet d'ajouter la m�tadonn�e pass�e en param�tre � la lettrine.
     *Elle affecte la liste de m�tadonn�es metadonnees en y ajoutant la m�tadonn�e pass�e en param�tre.
     * @param meta Metadonnee : metadonn�e � ajouter
     * @see Metadonnee
     */
    public void AjouterMetadonnees(Metadonnee meta) {
        if(meta!=null){
            if(metadonnees.contains(meta)==false) {
                metadonnees.add(meta);
            }
        }
    }

    /**
     * Cette m�thode permet de supprimer la m�tadonn�e pass�e en param�tre � la lettrine.
     * Elle affecte la liste de m�tadonn�es metadonnees en en retirant la m�tadonn�e pass�e en param�tre.
     * @param meta : m�tadonn�e � supprimer
     * @see Metadonnee
     */
    public void SupprimerMetadonnees(Metadonnee meta) {
        metadonnees.remove(meta);
    }

    /**
     * Permet de verifier si 2 objets sont exactement similaires
     *
     * @param objet l'objet à comparer
     * @return renvoie true si les deux objets sont similaires, false sinons
     */
    @Override
    public Boolean estCLone(Lettrine objet) {
        if(objet==null){
            return false;
        }
        if(!objet.getLien().equals(this.getLien())){
            return false;
        }
        if(!objet.getOuvrage().equals(this.getOuvrage())){
            return false;
        }
        if(objet.getId()!=this.getId()){
            return false;
        }
        if(objet.getNbPage()!=this.getNbPage()){
            return false;
        }
        for(Tag tag: this.tags){
            if(!objet.getTags().contains(tag)){
                return false;
            }
        }
        for(Metadonnee meta: metadonnees){
            if(!objet.getMetadonnees().contains(meta)){
                return false;
            }
        }
        return true;
    }
}