/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Whole.ccmsPackage;

import Whole.daoPackage.AbstractDAO;

import java.util.*;


// ----------- << imports@AAAAAAGEEKiFAPb0eJU= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEEKiFAPb0eJU= >>
// ----------- >>
public class Ouvrage implements CCMS {
    // ----------- << attribute.annotations@AAAAAAGEE5kHfev4KiE= >>
    // ----------- >>
    private String titre;

    // ----------- << attribute.annotations@AAAAAAGEE5lN1O6Hp5M= >>
    // ----------- >>
    private ArrayList<Auteur> auteurs;

    // ----------- << attribute.annotations@AAAAAAGEE6CrXOnszyc= >>
    // ----------- >>
    private String editeur;

    // ----------- << attribute.annotations@AAAAAAGEE6DZyu0dPGA= >>
    // ----------- >>
    private String imprimeur;

    // ----------- << attribute.annotations@AAAAAAGEE6UodQ/hdiQ= >>
    // ----------- >>
    private String lieuEdition;

    // ----------- << attribute.annotations@AAAAAAGEE6WSghIoOu0= >>
    // ----------- >>
    private String dateEdition;

    // ----------- << attribute.annotations@AAAAAAGEE6YCzhax948= >>
    // ----------- >>
    private int nbPage;

    // ----------- << attribute.annotations@AAAAAAGEE6ZHdhiMUGE= >>
    // ----------- >>
    private String lien;

    // ----------- << attribute.annotations@AAAAAAGEE6kJJjryfrU= >>
    // ----------- >>
    private int id;

    public Ouvrage(String titre, ArrayList<Auteur> auteurs, String editeur, String imprimeur, String lieuEdition, String dateEdition, int nbPage, String lien, int id) {
        this.titre = titre;
        this.auteurs = auteurs;
        this.editeur = editeur;
        this.imprimeur = imprimeur;
        this.lieuEdition = lieuEdition;
        this.dateEdition = dateEdition;
        this.nbPage = nbPage;
        this.lien = lien;
        this.id = id;
    }
    /**
     * Constructeur à utiliser pour les instances de changement
     */
    public Ouvrage() {
        this.id = -2;
        this.nbPage = -2;

    }

    private String getTitre() {
        return titre;
    }

    private ArrayList<Auteur> getAuteurs() {
        return auteurs;
    }

    private String getEditeur() {
        return editeur;
    }

    private String getImprimeur() {
        return imprimeur;
    }

    private String getLieuEdition() {
        return lieuEdition;
    }

    private String getDateEdition() {
        return dateEdition;
    }

    private int getNbPage() {
        return nbPage;
    }

    private String getLien() {
        return lien;
    }

    private int getId() {
        return id;
    }

    private void setTitre(String titre) {
        this.titre = titre;
    }

    private void setAuteurs(ArrayList<Auteur> auteurs) {
        this.auteurs = auteurs;
    }

    private void setEditeur(String editeur) {
        this.editeur = editeur;
    }

    private void setImprimeur(String imprimeur) {
        this.imprimeur = imprimeur;
    }

    private void setLieuEdition(String lieuEdition) {
        this.lieuEdition = lieuEdition;
    }

    private void setDateEdition(String dateEdition) {
        this.dateEdition = dateEdition;
    }

    private void setNbPage(int nbPage) {
        this.nbPage = nbPage;
    }

    private void setLien(String lien) {
        this.lien = lien;
    }

    private void setId(int id) {
        this.id = id;
    }

    /**
     * Modifie un CCMS, appel une méthode d'un objet de type AbstractDAO
     *
     * @see AbstractDAO
     */
    @Override
    public void modifier() {

    }

    /**
     * Cherche un CCMS, appel une méthode d'un objet de type AbstractDAO
     *
     * @see AbstractDAO
     */
    @Override
    public void chercher() {

    }

    /**
     * Créer un CCMS, appel une méthode d'un objet de type AbstractDAO
     *
     * @see AbstractDAO
     */
    @Override
    public void creer() {

    }

    /**
     * Supprime un CCMS, appel une méthode d'un objet de type AbstractDAO
     *
     * @see AbstractDAO
     */
    @Override
    public void supprimer() {

    }
}