/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Whole.ccmsPackage;

import Whole.daoPackage.AbstractDAO;

/**
 * Classe représentant les tags
 */
public class Tag implements CCMS {

    private int id;


    private String nom;


    private String description;

    /**
     * Constructeur de la classe tag à utilisé en cas normal
     * @param id l'identifiant du tag dans la bd
     * @param nom le nom du tag
     * @param description la description du tag

     */
    public Tag(int id, String nom, String description) {
        this.id = id;
        this.nom = nom;
        this.description = description;
    }
    /**
     * Constructeur à utiliser pour les instances de changement
     */
    public Tag() {
        this.id = -2;
    }

    /**
     * permet de renvoyer l'id du tag dans la base de données
     * @return id int
     */
    private int getId() {
        return id;
    }
    /**
     * permet de renvoyer le nom du tag dans la base de données
     * @return nom String
     */
    private String getNom() {
        return nom;
    }
    
    /**
     * permet de renvoyer la description du tag dans la base de données
     * @return description String
     */
    private String getDescription() {
        return description;
    }
    
    /**
     * permet de remplacer le nom du tag dans la base de données
     * @param nom String
     * @return nom String
     */
    private void setNom(String nom) {
        this.nom = nom;
    }
    /**
     * permet de remplacer la description du tag dans la base de données
     * @param description String
     * @return description String
     */
    private void setDescription(String description) {
        this.description = description;
    }

    /**
     * Modifie un Tag, appel la méthode modifier d'un objet de type AbstractDAO
     *
     * @see Whole.daoPackage.TagDAO
     */
    @Override
    public void modifier() {

    }

    /**
     * Cherche un Tag, appel la méthode chercher d'un objet de type AbstractDAO
     *
     * @see Whole.daoPackage.TagDAO
     */
    @Override
    public void chercher() {

    }

    /**
     * Créer un Tag, appel la méthode créer d'un objet de type AbstractDAO
     *
     * @see Whole.daoPackage.TagDAO
     */
    @Override
    public void creer() {

    }

    /**
     * Supprime un Tag, appel la méthode supprimer d'un objet de type AbstractDAO
     *
     * @see Whole.daoPackage.TagDAO
     */
    @Override
    public void supprimer() {

    }

}