/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Whole.exportPackage;

import java.io.File;
import java.sql.ResultSet;
import java.util.*;
import java.time.*;



/**
 * Implémentation de ExportTypeIntetface pour le SQL
 * @see ExportTypeInterface
 */
public class ExportSQL implements ExportTypeInterface {
    @Override
    /**
     *  Implémante en SQL la sauvegarde de la base de donnée dans un fichier
     * @param f Fichier de sauvegarde
     * @return true si la base peut être exportée, false sinon
     * @see whole.AdminDao.exportDonee
     */
    public Boolean export(File f, ResultSet rs) {
        return true;
    }

}