/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Whole.exportPackage;

import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;

/**
 * Interface qui permet d'ajouter facilement des nouvelles méthodes d'export
 */
public interface ExportTypeInterface {

    /**
     *  Implémante d'une manière à définir la sauvegarde de la base de donnée dans un fichier
     * @param f Fichier de sauvegarde
     * @param rs L'intégralité d'une base
     * @return true si la base peut être exportée, false sinon
     * @see Whole.daoPackage.AdminDAO#exportDonee(File, Connection, ExportTypeInterface)
     * @see File
     * @see ResultSet
     */
    Boolean export(File f, ResultSet rs);

    // ----------- << method.annotations@AAAAAAGEzpbIUAevq+k= >>
    // ----------- >>

}