/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Whole.exportPackage;

import java.io.File;

/**
 * Interface qui permet d'ajouter facilement des nouvelles méthodes d'export
 */
public interface ExportTypeInterface {

    /**
     *  Implémante d'une manière à définir la sauvegarde de la base de donnée dans un fichier
     * @param f Fichier de sauvegarde
     * @see whole.AdminDao.exportDonee
     */
    void export(File f);

    // ----------- << method.annotations@AAAAAAGEzpbIUAevq+k= >>
    // ----------- >>

}