/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Whole.exportPackage;

import java.io.File;
import Whole.daoPackage.AbstractDAO;

/**
 * Implémentation de ExportTypeIntetface pour le SQL
 * @see ExportTypeInterface
 */
public class ExportCSV implements ExportTypeInterface {

    /**
     *  Implémante en CSV la sauvegarde de la base de donnée dans un fichier
     * @param f Fichier de sauvegarde
     * @see Whole.daoPackage.AbstractDAO
     */
    @Override
    public void export(File f) {

    }

}