/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package whole.exportPackage;

import java.io.File;


// ----------- << imports@AAAAAAGEzpgiZ2u/fBo= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEzpgiZ2u/fBo= >>
// ----------- >>
public class ExportCSV implements ExportTypeInterface {
    @Override
    // ----------- << method.annotations@AAAAAAGEzpbIUAevq+k= >>
    // ----------- >>
    public void export(File f) {
    // ----------- << method.body@AAAAAAGEzpbIUAevq+k= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGEzpgiZ2u/fBo= >>
// ----------- >>
}