/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Whole.exportPackage;

import java.io.File;
import java.sql.ResultSet;
import java.util.*;
import java.time.*;



/**
 * Implémentation de ExportTypeIntetface pour le SQL
 * @see ExportTypeInterface
 */
public class ExportSQL implements ExportTypeInterface {
    String name="SQL";




    /**
     * Ne pas utiliser
     * @param f Fichier de sauvegarde
     * @return renvoir toujours false, n'est pas sensé être appelé
     *
     * @see Whole.daoPackage.AbstractDAO
     */
    @Override
    @Deprecated
    public Boolean export(File f, ArrayList<ArrayList<String>> list) {
        return false;
    }
    /**
     *  Implémante en CSV la sauvegarde de la base de donnée dans un fichier
     * @param f Fichier de sauvegarde
     * @return true si la base peut être exportée, false sinon
     *
     * @see Whole.daoPackage.AbstractDAO
     */
    public Boolean export(File f){
        return true;
    }

}