/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Whole.exportPackage;

import java.io.File;
import java.util.*;
import java.time.*;



/**
 * Implémentation de ExportTypeIntetface pour le SQL
 * @see ExportTypeInterface
 */
public class ExportXLS implements ExportTypeInterface {
    /**
     *  Implémante en XLS la sauvegarde de la base de donnée dans un fichier
     * @param f Fichier de sauvegarde
     * @see whole.AdminDao.exportDonee
     */
    @Override
    public void export(File f) {

    }

}