/*
 * This code has been generated by the Rebel: a code generator for modern Java.
 *
 * Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
 */
package Whole.exportPackage;


import java.io.*;

import java.util.ArrayList;


/**
 * Implémentation de ExportTypeIntetface pour le SQL
 *
 * @see ExportTypeInterface
 */
public class ExportCSV extends ExportTypeInterface {


    @Override
    /**
     *  Implémante en SQL la sauvegarde de la base de donnée dans un fichier
     * @param f Fichier de sauvegarde
     * @return true si la base peut être exportée, false sinon
     * @see whole.AdminDao.exportDonee
     */
    public Boolean export(File f, ArrayList<ArrayList<String>> list) {
        try {
            BufferedWriter br = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(f)));
            for (ArrayList<String> strings : list) {
                if (strings != null) {
                    for (int j = 0; j < strings.size(); j++) {
                        if (strings.get(j) != null) {
                            br.write(escapeSpecialCharacters(strings.get(j)));
                        }
                        else
                            br.write("null");
                        if (j + 1 < strings.size()) {
                            br.write(", ");
                        }
                    }
                }

                br.newLine();
            }
            br.close();
        } catch (FileNotFoundException e) {
            throw new RuntimeException(e);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        return true;
    }

    @Override
    public String getName() {
        return name;
    }

    /**
     * .
     * Permet de gerer les caractères spéciaux en csv, issus de https://www.baeldung.com/java-csv
     *
     * @param data une chaine de charactère avec potentiellement des caractères spéciaux problématiques en csv
     * @return une chaine de charactère sans caractères spéciaux problématiques en csv
     */
    public static String escapeSpecialCharacters(String data) {
        String escapedData = null;
        if (data != null) {
            escapedData = data.replaceAll("\\R", " ");
            if (data.contains(",") || data.contains("\"") || data.contains("'")) {
                data = data.replace("\"", "\"\"");
                escapedData = "\"" + data + "\"";
            }
        }
        return escapedData;
    }

    public ExportCSV() {
        super("CSV");
    }
}