/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Whole.exportPackage;

import java.io.File;

import java.util.ArrayList;

/**
 * Interface qui permet d'ajouter facilement des nouvelles méthodes d'export
 */
public abstract class ExportAbstract {

    public String name="null";
    /**
     *  Implémante d'une manière à définir la sauvegarde de la base de donnée dans un fichier
     * @param path chemin d'accès
     * @param list L'intégralité d'une table
     * @return true si la base peut être exportée, false sinon
     * @see Whole.daoPackage.AdminDAO#exportDonnee(String, String) 
     * @see File
     */
    public abstract Boolean export(String path, ArrayList<ArrayList<String>> list);
    abstract String getName();

    public ExportAbstract(String name) {
        this.name = name;
    }
}