/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package whole;

import java.io.File;
import java.sql.Connection;
import java.util.*;
import java.time.*;


public class AdminDao {
    private static Connection cn;

    /**
     * Permet de stocker dans un fichier la bd
    * @param file le fichier où sera exporter les données
     * @see whole.exportPackage.ExportTypeInterface
    */


    public void exportDonee(File file) {

    }
    /**
     * Permet de stocker dans un fichier les logs
     * @param file le fichier où sera exporter les logs
     */


    public void exportLog(File file) {

    }

    /**
     * Supprime les logs de la bd
     */
    public void deleteLog() {

    }

}