/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package whole;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEzpKTNDlXH7I= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEzpKTNDlXH7I= >>
// ----------- >>
public class AdminDao {
    /**
    * @param file
    */

    // ----------- << method.annotations@AAAAAAGEzpSgDJiRGIY= >>
    // ----------- >>
    public void exportDonee(File file) {
    // ----------- << method.body@AAAAAAGEzpSgDJiRGIY= >>
    // ----------- >>
    }
    /**
    * @param file
    */

    // ----------- << method.annotations@AAAAAAGEzpT/0ar5GIQ= >>
    // ----------- >>
    public void exportLog(File file) {
    // ----------- << method.body@AAAAAAGEzpT/0ar5GIQ= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEzpUiRLRKiMQ= >>
    // ----------- >>
    public void deleteLog() {
    // ----------- << method.body@AAAAAAGEzpUiRLRKiMQ= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGEzpKTNDlXH7I= >>
// ----------- >>
}