/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package whole;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEesQU7gHhxJ8= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEesQU7gHhxJ8= >>
// ----------- >>
public class AuteurDAO extends AbstractDao {
// ----------- << class.extras@AAAAAAGEesQU7gHhxJ8= >>
// ----------- >>
}