/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package whole;


public class Auteur implements CCMS {
    // ----------- << attribute.annotations@AAAAAAGEE6k55EBSKXE= >>
    // ----------- >>
    private int id;


    private String nom;

    // ----------- << attribute.annotations@AAAAAAGEE6mNZEPAXTM= >>
    // ----------- >>
    private String prenom;

    private int getId() {
        return id;
    }

    private String getNom() {
        return nom;
    }

    private String getPrenom() {
        return prenom;
    }

    private void setId(int id) {
        this.id = id;
    }

    private void setNom(String nom) {
        this.nom = nom;
    }

    private void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    @Override
    // ----------- << method.annotations@AAAAAAGEhQVIZ3GA1Hc= >>
    // ----------- >>
    public void modifier() {
    // ----------- << method.body@AAAAAAGEhQVIZ3GA1Hc= >>
    // ----------- >>
    }
    @Override
    // ----------- << method.annotations@AAAAAAGEhQV/ynS3l3E= >>
    // ----------- >>
    public void chercher() {
    // ----------- << method.body@AAAAAAGEhQV/ynS3l3E= >>
    // ----------- >>
    }
    @Override
    // ----------- << method.annotations@AAAAAAGEhQbETnhUTaM= >>
    // ----------- >>
    public void creer() {
    // ----------- << method.body@AAAAAAGEhQbETnhUTaM= >>
    // ----------- >>
    }
    @Override
    // ----------- << method.annotations@AAAAAAGEhQkzMzpAvXM= >>
    // ----------- >>
    public void supprimer() {
    // ----------- << method.body@AAAAAAGEhQkzMzpAvXM= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGEE5woOiUo4O8= >>
// ----------- >>
}