/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package whole;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEEKoSJ/gdFKw= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEEKoSJ/gdFKw= >>
// ----------- >>
public interface CCMS {
    // ----------- << method.annotations@AAAAAAGEhQVIZ3GA1Hc= >>
    // ----------- >>
    void modifier();
    // ----------- << method.annotations@AAAAAAGEhQV/ynS3l3E= >>
    // ----------- >>
    void chercher();
    // ----------- << method.annotations@AAAAAAGEhQbETnhUTaM= >>
    // ----------- >>
    void creer();
    // ----------- << method.annotations@AAAAAAGEhQkzMzpAvXM= >>
    // ----------- >>
    void supprimer();
// ----------- << interface.extras@AAAAAAGEEKoSJ/gdFKw= >>
// ----------- >>
}