/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package whole;

import java.io.File;




public class Fenetre {
    /**
    * @param s Scene
    */

    // ----------- << method.annotations@AAAAAAGEFFMIn3R+xuw= >>
    // ----------- >>
    public Boolean afficher(void s Scene) {
    // ----------- << method.body@AAAAAAGEFFMIn3R+xuw= >>
    // ----------- >>
    }
    public File savePopUp(){
        return null;
    }
// ----------- << class.extras@AAAAAAGEEKeR9vafVXg= >>
// ----------- >>
}