/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package whole;


// ----------- << imports@AAAAAAGEE5qV6vFwH5E= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEE5qV6vFwH5E= >>
// ----------- >>
public class Metadonnee {
    // ----------- << attribute.annotations@AAAAAAGEE6zXdR7UaOE= >>
    // ----------- >>
    private Lettrine lettrine;
    private String nom;

    // ----------- << attribute.annotations@AAAAAAGEE6z/dyCLQ5I= >>
    // ----------- >>
    private int id;

    // ----------- << attribute.annotations@AAAAAAGEE60iQyJCOoE= >>
    // ----------- >>
    private String entree;

    // ----------- << attribute.annotations@AAAAAAGEE61uPSP57OM= >>
    // ----------- >>
    private String unite;

    // ----------- << attribute.annotations@AAAAAAGEE62pqCWwxiQ= >>
    // ----------- >>
    private String description;

    private String getNom() {
        return nom;
    }

    private int getId() {
        return id;
    }

    private String getEntree() {
        return entree;
    }

    private String getUnite() {
        return unite;
    }

    private String getDescription() {
        return description;
    }

    private void setNom(String nom) {
        this.nom = nom;
    }

    private void setId(int id) {
        this.id = id;
    }

    private void setEntree(String entree) {
        this.entree = entree;
    }

    private void setUnite(String unite) {
        this.unite = unite;
    }

    private void setDescription(String description) {
        this.description = description;
    }

    /**
    * @param meta
    */

    // ----------- << method.annotations@AAAAAAGEdlwMksQ43p0= >>
    // ----------- >>
    public void Modifier(Metadonnee meta) {
    // ----------- << method.body@AAAAAAGEdlwMksQ43p0= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGEE5qV6vFwH5E= >>
// ----------- >>
}