/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package whole;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEetK2p7r0tYM= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEetK2p7r0tYM= >>
// ----------- >>
public class SIngleConnection {
    /**
    * @param url 
    * @param login 
    * @param pwd
    */

    // ----------- << method.annotations@AAAAAAGEetQLSPKw430= >>
    // ----------- >>
    public Connection connection(String url, String login, String pwd) {
    // ----------- << method.body@AAAAAAGEetQLSPKw430= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGEetK2p7r0tYM= >>
// ----------- >>
}