/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package whole;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEEKketvcezw8= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEEKketvcezw8= >>
// ----------- >>
public class Tag implements CCMS {
    // ----------- << attribute.annotations@AAAAAAGEE6qQjWdBWHI= >>
    // ----------- >>
    private int id;

    // ----------- << attribute.annotations@AAAAAAGEE6rkXmsqMsw= >>
    // ----------- >>
    private String nom;

    // ----------- << attribute.annotations@AAAAAAGEE6s4xW0Fm4U= >>
    // ----------- >>
    private String description;

    private int getId() {
        return id;
    }

    private String getNom() {
        return nom;
    }

    private String getDescription() {
        return description;
    }

    private void setId(int id) {
        this.id = id;
    }

    private void setNom(String nom) {
        this.nom = nom;
    }

    private void setDescription(String description) {
        this.description = description;
    }

    @Override
    // ----------- << method.annotations@AAAAAAGEhQVIZ3GA1Hc= >>
    // ----------- >>
    public void modifier() {
    // ----------- << method.body@AAAAAAGEhQVIZ3GA1Hc= >>
    // ----------- >>
    }
    @Override
    // ----------- << method.annotations@AAAAAAGEhQV/ynS3l3E= >>
    // ----------- >>
    public void chercher() {
    // ----------- << method.body@AAAAAAGEhQV/ynS3l3E= >>
    // ----------- >>
    }
    @Override
    // ----------- << method.annotations@AAAAAAGEhQbETnhUTaM= >>
    // ----------- >>
    public void creer() {
    // ----------- << method.body@AAAAAAGEhQbETnhUTaM= >>
    // ----------- >>
    }
    @Override
    // ----------- << method.annotations@AAAAAAGEhQkzMzpAvXM= >>
    // ----------- >>
    public void supprimer() {
    // ----------- << method.body@AAAAAAGEhQkzMzpAvXM= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGEEKketvcezw8= >>
// ----------- >>
}