/*
 * This code has been generated by the Rebel: a code generator for modern Java.
 *
 * Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
 */
package Whole.daoPackage;

import Whole.LinkToDb;
import Whole.exportPackage.ExportTypeInterface;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Classe permettant à l'administrateur de gérer la base de donnée
 */
public class AdminDAO<E extends ExportTypeInterface> {

    /**
     * Constructeur de la classe
     */
    public AdminDAO() {
    }

    /**
     * Permet de stocker dans un fichier la bd
     * @param file le fichier où sera exporter les données
     * @param cn La connection à la base de donnée
     * @see LinkToDb
     * @see Whole.exportPackage.ExportTypeInterface
     *
     */


    public Boolean exportDonee(File file,Connection cn, E e) {
        return e.export(file);
    }
    /**
     * Permet de stocker dans un fichier les logs
     * @param cn La connection à la base de donnée
     * @param file le fichier où sera exporter les log
     * @see LinkToDb
     */


    public Boolean exportLog(File file,Connection cn)  {
        try {
            Statement stmt = cn.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT `text`,`date`,`userLogin` FROM `log`");
            String str = "Hello";
            BufferedWriter bw = new BufferedWriter(new FileWriter(file));
            bw.write("Log exporté le "+System.currentTimeMillis());
            while(rs.next()){
                str=rs.getString(2)+" par "+rs.getString(3)+": "+rs.getString(1);
                bw.write(str);
                bw.newLine();

            }
            bw.close();

        }catch(SQLException e){
            System.err.println("something went wrong with the database link");
        } catch (IOException e) {
            System.err.println("something went wrong with the writing of the file");

        }
        return false;
    }

    /**
     * Supprime les logs de la bd
     * @param cn La connection à la base de donnée
     * @see LinkToDb
     *
     */
    public void deleteLog(Connection cn) {

    }

    /**
     * Ajoute au log un text
     * @param txt Le message à enregistrer
     * @param user L'utilisateur qui a provoqué une action
     * @param cn La connection à la base de donnée
     * @see LinkToDb
     */
    public void writeLog(String txt, String user,Connection cn){

    }

}