/*
 * This code has been generated by the Rebel: a code generator for modern Java.
 *
 * Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
 */
package Whole.daoPackage;

import Whole.LinkToDb;

import java.io.File;
import java.sql.Connection;
/**
 * Classe permettant à l'administrateur de gérer la base de donnée
 */
public class AdminDAO {




    /**
     * Constructeur de la classe
     */
    public AdminDAO() {
    }

    /**
     * Permet de stocker dans un fichier la bd
     * @param file le fichier où sera exporter les données
     * @param cn La connection à la base de donnée
     * @see LinkToDb
     * @see Whole.exportPackage.ExportTypeInterface
     *
     */


    public void exportDonee(File file,Connection cn) {

    }
    /**
     * Permet de stocker dans un fichier les logs
     * @param cn La connection à la base de donnée
     * @param file le fichier où sera exporter les log
     * @see LinkToDb
     */


    public void exportLog(File file,Connection cn) {

    }

    /**
     * Supprime les logs de la bd
     * @param cn La connection à la base de donnée
     * @see LinkToDb
     *
     */
    public void deleteLog(Connection cn) {

    }

    /**
     * Ajoute au log un text
     * @param txt Le message à enregistrer
     * @param user L'utilisateur qui a provoqué une action
     * @param cn La connection à la base de donnée
     * @see LinkToDb
     */
    public void writeLog(String txt, String user,Connection cn){

    }

}