/*
 * This code has been generated by the Rebel: a code generator for modern Java.
 *
 * Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
 */
package Whole.daoPackage;

import Whole.ccmsPackage.Auteur;

import java.io.File;
import java.sql.Connection;
/**
 * Classe permettant à l'administrateur de gérer la base de donnée
 */
public class AdminDAO {
    private static Connection cn;

    /**
     * Permet de stocker dans un fichier la bd
     * @param file le fichier où sera exporter les données
     * @see Whole.exportPackage.ExportTypeInterface
     */


    public void exportDonee(File file) {

    }
    /**
     * Permet de stocker dans un fichier les logs
     * @param file le fichier où sera exporter les logs
     */


    public void exportLog(File file) {

    }

    /**
     * Supprime les logs de la bd
     */
    public void deleteLog() {

    }

    /**
     * Ajoute au log un text
     * @param txt Le message à enregistrer
     * @param user L'utilisateur qui a provoqué une action
     */
    public void writeLog(String txt, String user){

    }

}