/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Whole.daoPackage;

import Whole.ccmsPackage.Lettrine;
import Whole.ccmsPackage.Ouvrage;
import Whole.ccmsPackage.Tag;


public class LettrineDAO extends AbstractDAO {
    /**
    * @param l1 Lettrine 
    * @param l2 Lettrine
    */

    public void lie(Lettrine l1 , Lettrine l2 ) {

    }
    /**
    * @param l Lettrine 
    * @param O ouvrage
    */


    public void provient(Lettrine l , Ouvrage O ) {

    }
    /**
    * @param l Lettrine 
    * @param t Tag
    */


    public void tager(Lettrine l , Tag t ) {

    }

}