/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Whole.daoPackage;

import Whole.ccmsPackage.Auteur;
import Whole.ccmsPackage.Ouvrage;
import Whole.daoPackage.AbstractDAO;
/**
 * Classe servant à lié à la base de donnée les méthodes d'Auteurs
 * @see Ouvrage
 */
public class OuvrageDAO extends AbstractDAO {
    /**
    * @param a Auteur 
    * @param o Ouvrage
    */
    public void ecrit( Auteur a, Ouvrage o) {

    }
}