/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Whole.daoPackage;

import Whole.ccmsPackage.Tag;

import java.sql.Connection;
import java.util.ArrayList;
/**
 * Classe servant à lié à la base de donnée les méthodes de Tag
 * @see Tag
 */
public class TagDAO extends AbstractDAO {
    private static Connection cn;
    /**
     * Constructeur de la classe OuvrageDAO. Instancie l'objet Connection
     * cn avec le cn passe en parametre.
     *
     * @param cn objet Connection provenant de SingleConnection
     * @see Connection
     * @see Whole.SingleConnection
     */
    public TagDAO(Connection cn) {
        super(cn);
    }

    /**
     * Met à jour la BD
     * @param objet Tag à changer
     * @param changement Tag de changement (les paramètres null ne sont pas à changer)
     */


    public void modifier(Tag objet , Tag changement ) {

    }
    /**
     * Supprime de la db un Tag
     * @param objet un Tag d'un type à déterminer dans chaque implémentation
     * @see Tag
     */

    public void supprimer(Tag objet ) {

    }
    /**
     * Ajoute à la base de donnée un Tag
     * @param donne le Tag à ajouter
     * @see Tag
     */

    public void creer(Tag donne) {

    }
    /**
     *Cherche un Tag dans la base
     * @param donne Tag avec tout les paramètres nuls sauf ceux à chercher
     * @see Tag
     */

    public ArrayList<Tag> chercher(Tag donne) {
        return null;
    }
}