/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Whole;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEE5yCdUieF1o= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEE5yCdUieF1o= >>
// ----------- >>
public abstract class AbstractDao {
    // ----------- << attribute.annotations@AAAAAAGEE4dM2ZIpTbM= >>
    // ----------- >>
    private static Connection cn;

    /**
    * @param objet  
    * @param changement
    */

    // ----------- << method.annotations@AAAAAAGEE4qS0JvDFhc= >>
    // ----------- >>
    public Boolean modifier(CCMS objet , CCMS changement ) {
    // ----------- << method.body@AAAAAAGEE4qS0JvDFhc= >>
    // ----------- >>
    }
    /**
    * @param objet
    */

    // ----------- << method.annotations@AAAAAAGEE4wyOaBHozw= >>
    // ----------- >>
    public Boolean supprimer(CCMS objet ) {
    // ----------- << method.body@AAAAAAGEE4wyOaBHozw= >>
    // ----------- >>
    }
    /**
    * @param donne
    */

    // ----------- << method.annotations@AAAAAAGEE7L+kh2QhOo= >>
    // ----------- >>
    public CCMS creer(CCMS donne) {
    // ----------- << method.body@AAAAAAGEE7L+kh2QhOo= >>
    // ----------- >>
    }
    /**
    * @param donne
    */

    // ----------- << method.annotations@AAAAAAGEE7T9TEE3oMU= >>
    // ----------- >>
    public ArrayList<CCMS> chercher(CCMS donne) {
    // ----------- << method.body@AAAAAAGEE7T9TEE3oMU= >>
    // ----------- >>
    }
    /**
    * @param donne
    */

    // ----------- << method.annotations@AAAAAAGEIHgn8/2P5wo= >>
    // ----------- >>
    public void synchronise(CCMS donne) {
    // ----------- << method.body@AAAAAAGEIHgn8/2P5wo= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGEE5yCdUieF1o= >>
// ----------- >>
}