/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Whole;

import java.sql.Connection;
import java.util.*;

public abstract class AbstractDAO {

    private static Connection cn;

    /**
    * @param objet  
    * @param changement
    */


    public Boolean modifier(CCMS objet , CCMS changement ) {

    }
    /**
     * Supprime de la db un CCMS
    * @param objet un CCMS d'un type à déterminer dans chaque implémentation
     *
    */

    public void supprimer(CCMS objet ) {

    }
    /**
    * @param donne
    */

    public CCMS creer(CCMS donne) {

    }
    /**
    * @param donne
    */

    public ArrayList<CCMS> chercher(CCMS donne) {

    }

}