/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Whole;

public class Auteur implements CCMS {
    // ----------- << attribute.annotations@AAAAAAGEE6k55EBSKXE= >>
    // ----------- >>
    private int id;

    // ----------- << attribute.annotations@AAAAAAGEE6lpf0It0Aw= >>
    // ----------- >>
    private String nom;

    // ----------- << attribute.annotations@AAAAAAGEE6mNZEPAXTM= >>
    // ----------- >>
    private String prenom;

    private int getId() {
        return id;
    }

    private String getNom() {
        return nom;
    }

    private String getPrenom() {
        return prenom;
    }

    private void setId(int id) {
        this.id = id;
    }

    private void setNom(String nom) {
        this.nom = nom;
    }

    private void setPrenom(String prenom) {
        this.prenom = prenom;
    }

// ----------- << class.extras@AAAAAAGEE5woOiUo4O8= >>
// ----------- >>
}