/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Whole;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEEKoSJ/gdFKw= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEEKoSJ/gdFKw= >>
// ----------- >>
public interface CCMS {
// ----------- << interface.extras@AAAAAAGEEKoSJ/gdFKw= >>
// ----------- >>
}