/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Whole;

import Whole.daoPackage.OuvrageDAO;

import java.sql.Connection;

/**
* Coeur de l'application, doit avant tout lancer ConnectionUniqueBD
*/
public class Controleur {
	
	 /**
	 *connection a la base de donn�e
	 */
    private Connection bd;

    /**
    * Permet de sauvegarder des métadonnés (ou autre) dans le but d'un copier coller
    */
    private Object pressePapier;
    /**
     *getter de bd
     *
     */
    private Connection getBd() {
        return bd;
    }
    /**
     *getter de PressePapier
     */
    private Object getPressePapier() {
        return pressePapier;
    }
    /**
     *setter de bd 
     */
    private void setBd(Connection bd) {
        this.bd = bd;
    }

    /**
     * Permet de sauvegarder n'importe quel type dans le but d'un copier coller
     * @param objet, objet à copier
     */
    private void setPressePapier(Object objet) {
        this.pressePapier = pressePapier;
    }

    /**
    * Permet de se connecter a la base de donnee en faisant un appel de SingleConnection avec les parametres choisis
    * @param name nom d'utilisateur
    * @param pwd mot de passe
     * @return True si l'utilisateur est connecté, false sinon
    * @see LinkToDb
    */
    public Boolean Login( String name,  String pwd) {
        return true;
    }
    /**
     * Demande a utilisateurDAO de creer un utilisateur
    * @param  name nom d'utilisateur
    * @param  pwd mot de passe
    * @param  confirm confirmation du mot de passe
     * @return true si l'utilisateur a pu être aouté, false sino,
    */
    public Boolean AddUser(String name, String pwd, String confirm) {
        return true; //en attendant de coder la fonction
    }
     /**
     * Permet le changement de mot de passe en en remplacent l'ancien demander par un nouveau tout en le confirmant 
    * @param name String 
    * @param oldPwd String 
    * @param newPwd String 
    * @param confirm String
      * @return true si le mot de passe à pu être changé, false sinon
    */
    public Boolean ChnagePWD(String name, String oldPwd, String newPwd, String confirm) {
        return true;
    }
    public static Boolean init(){
        return false;
    }

}