/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Whole;

import java.sql.Connection;
import java.util.*;
import java.time.*;

/**
* Coeur de l'application, doit avant tout lancer COnnectionUniqueBD
*/
public class Controleur {
	
	 /**
	 *connection a la base de donn�e
	 */
    private Connection bd;

    /**
    * Permet de sauvegarder des métadonnés (ou autre) dans le but d'un copier coller
    */
    private Object pressePapier;
    /**
     *getter de bd
     */
    private Connection getBd() {
        return bd;
    }
    /**
     *getter de PressePapier
     */
    private Object getPressePapier() {
        return pressePapier;
    }
    /**
     *setter de bd 
     */
    private void setBd(Connection bd) {
        this.bd = bd;
    }
    /**
     * Permet de sauvegarder des métadonnés (ou autre) dans le but d'un copier coller
     */
    private void setPressePapier(Object pressePapier) {
        this.pressePapier = pressePapier;
    }

    /**
    * Permet de se connecter a la base de donnee en faisant un appel de SingleConnection avec les parametres choisis
    * @param String name nom d'utilisateur
    * @param String pwd mot de passe
    * @see SingleConnection
    */
    public Boolean Login( String name,  String pwd) {
        return true;
    }
    /**
     * Demande a utilisateurDAO de creer un utilisateur
    * @param String name nom d'utilisateur
    * @param String pwd mot de passe
    * @param String confirm confirmation du mot de passe 
    */
    public Boolean AddUser(String name, String pwd, String confirm) {
        return true; //en attendant de coder la fonction
    }
     /**
     * Permet le changement de mot de passe en en remplacent l'ancien demander par un nouveau tout en le confirmant 
    * @param name String 
    * @param oldPwd String 
    * @param newPwd String 
    * @param confirm String
    */
    public Boolean ChnagePWD(String name, String oldPwd, String newPwd, String confirm) {
        return true;
    }
}