/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Whole;

import java.sql.Connection;
import java.util.*;
import java.time.*;

/**
* Coeur de l'application, doit avant tout lancer COnnectionUniqueBD
*/
public class Controleur {

    private Connection bd;

    /**
    * Permet de sauvegarder des métadonnés (ou autre) dans le but d'un copier coller
    */
    private Object pressePapier;

    private Connection getBd() {
        return bd;
    }

    private Object getPressePapier() {
        return pressePapier;
    }

    private void setBd(Connection bd) {
        this.bd = bd;
    }

    private void setPressePapier(Object pressePapier) {
        this.pressePapier = pressePapier;
    }

    /**
    * @param name String
    * @param pwd String
    */
    public Boolean Login( String name,  String pwd) {
        return true;
    }
    /**
    * @param name String
    * @param pwd String
    * @param confirm String
    */
    public Boolean AddUser(String name, String pwd, String confirm) {
        return true; //en attendant de coder la fonction
    }
    /**
    * @param name String 
    * @param oldPwd String 
    * @param newPwd String 
    * @param confirm String
    */
    public Boolean ChnagePWD(String name, String oldPwd, String newPwd, String confirm) {
        return true;
    }
}