/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Whole;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEEKeR9vafVXg= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEEKeR9vafVXg= >>
// ----------- >>
public class Fenetre {
    /**
    * @param s Scene
    */

    // ----------- << method.annotations@AAAAAAGEFFMIn3R+xuw= >>
    // ----------- >>
    public Boolean afficher(void s Scene) {
    // ----------- << method.body@AAAAAAGEFFMIn3R+xuw= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGEEKeR9vafVXg= >>
// ----------- >>
}