/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Whole;

import javafx.scene.Scene;

import java.util.*;
import java.time.*;

public class Fenetre {

    /**
    * @param s Scene
    */
    public Boolean afficher(Scene s) {
        return true;
    }
}