/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Whole;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEEKlTM/dIQDY= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEEKlTM/dIQDY= >>
// ----------- >>
public class Lettrine implements CCMS {
    // ----------- << attribute.annotations@AAAAAAGEE6blvh6f+aY= >>
    // ----------- >>
    private Ouvrage ouvrage;

    // ----------- << attribute.annotations@AAAAAAGEE6c7UiKWdLo= >>
    // ----------- >>
    private ArrayList<Metadonnees> metadonnees;

    // ----------- << attribute.annotations@AAAAAAGEE6ebxicMu3w= >>
    // ----------- >>
    private int nbPage;

    // ----------- << attribute.annotations@AAAAAAGEE6jfbDkXR34= >>
    // ----------- >>
    private int id;

    // ----------- << attribute.annotations@AAAAAAGEE6odtWRFSiA= >>
    // ----------- >>
    private ArrayList<Tag> tags;

    private Ouvrage getOuvrage() {
        return ouvrage;
    }

    private ArrayList<Metadonnees> getMetadonnees() {
        return metadonnees;
    }

    private int getNbPage() {
        return nbPage;
    }

    private int getId() {
        return id;
    }

    private ArrayList<Tag> getTags() {
        return tags;
    }

    private void setOuvrage(Ouvrage ouvrage) {
        this.ouvrage = ouvrage;
    }

    private void setMetadonnees(ArrayList<Metadonnees> metadonnees) {
        this.metadonnees = metadonnees;
    }

    private void setNbPage(int nbPage) {
        this.nbPage = nbPage;
    }

    private void setId(int id) {
        this.id = id;
    }

    private void setTags(ArrayList<Tag> tags) {
        this.tags = tags;
    }

    // ----------- << method.annotations@AAAAAAGEJC33Ou5EqO4= >>
    // ----------- >>
    public void AjouterMetadonnees() {
    // ----------- << method.body@AAAAAAGEJC33Ou5EqO4= >>
    // ----------- >>
    }
    /**
    * @param meta
    */

    // ----------- << method.annotations@AAAAAAGEJC6p8/QYVKI= >>
    // ----------- >>
    public void SupprimerMetadonnees(Metadonnees meta) {
    // ----------- << method.body@AAAAAAGEJC6p8/QYVKI= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGEEKlTM/dIQDY= >>
// ----------- >>
}