/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Whole;

import java.util.*;

public class Lettrine implements CCMS {

    private Ouvrage ouvrage;

    /**
     * Liste des métadonnées associées à la lettrine
     */
    private ArrayList<Metadonnees> metadonnees;

    /**
     * numéro de la page sur laquelle figure la lettrine
     */
    private int nbPage;

    /**
     * id de la lettrine dans la base
     */
    private int id;

    /**
     * Liste des tags associés à la lettrine
     */
    private ArrayList<Tag> tags;

    /**
     * Constructeur de la classe Lettrine
     * @param ouvrage
     * @param metadonnees
     * @param nbPage
     * @param id
     * @param tags
     */
    public Lettrine(Ouvrage ouvrage, ArrayList<Metadonnees> metadonnees, int nbPage, int id, ArrayList<Tag> tags) {
        this.ouvrage = ouvrage;
        this.metadonnees = metadonnees;
        this.nbPage = nbPage;
        this.id = id;
        this.tags = tags;
    }

    /**
     * Renvoie un objet de type Ouvrage
     * @return Ouvrage ouvrage
     */
    private Ouvrage getOuvrage() {
        return ouvrage;
    }

    /**
     * Renvoie la liste des métadonnées associées à la lettrine
     * @return ArrayList<Metadonnees> metadonnees
     */
    private ArrayList<Metadonnees> getMetadonnees() {
        return metadonnees;
    }

    /**
     * Renvoie le numéro de la page sur laquelle la lettrine figure.
     * @return int nbPage
     */
    private int getNbPage() {
        return nbPage;
    }

    /**
     * Renvoie l'id de la lettrine dans la base de données
     * @return int id
     */
    private int getId() {
        return id;
    }

    /**
     * Renvoie la liste des tags associés à la lettrine
     * @return ArrayList<Tag> tags
     */
    private ArrayList<Tag> getTags() {
        return tags;
    }

    /**
     * permet de modifier la valeur de l'ouvrage par l'objet en paramètre
     * @param ouvrage : nouvelle valeur de ouvrage
     */
    private void setOuvrage(Ouvrage ouvrage) {
        this.ouvrage = ouvrage;
    }

    /**
     * permet de modifier la valeur du numéro de la page par l'objet en paramètre
     * @param nbPage : nouvelle valeur de nbPage
     */
    private void setNbPage(int nbPage) {
        this.nbPage = nbPage;
    }

    /**
     * Cette methode permet d'ajouter la métadonnée passée en paramètre à la lettrine.
     *Elle affecte la liste de métadonnées metadonnees en y ajoutant la métadonnée passée en paramètre.
     * @param meta : metadonnée à ajouter
     * @see #metadonnees
     */
    public void AjouterMetadonnees(Metadonnee meta) {

    }

    /**
     * Cette méthode permet de supprimer la métadonnée passée en paramètre à la lettrine.
     * Elle affecte la liste de métadonnées metadonnees en en retirant la métadonnée passée en paramètre.
     * @param meta : métadonnée à supprimer
     * @see #metadonnees
     */
    public void SupprimerMetadonnees(Metadonnees meta) {

    }
}