/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Whole;


// ----------- << imports@AAAAAAGEEKm5d/fG0Tk= >>
// ----------- >>

import Whole.ccmsPackage.Lettrine;
import Whole.ccmsPackage.Tag;

// ----------- << class.annotations@AAAAAAGEEKm5d/fG0Tk= >>
// ----------- >>
public class LettrineDAO extends AbstractDAO {
    /**
    * @param l1 Lettrine 
    * @param l2 Lettrine
    */

    // ----------- << method.annotations@AAAAAAGEIHo0vhVzv4g= >>
    // ----------- >>
    public void lie(void l1 Lettrine, void l2 Lettrine) {
    // ----------- << method.body@AAAAAAGEIHo0vhVzv4g= >>
    // ----------- >>
    }
    /**
    * @param l Lettrine 
    * @param O ouvrage
    */

    // ----------- << method.annotations@AAAAAAGEIHt5eyFqOnk= >>
    // ----------- >>
    public void provient(void l Lettrine, void O ouvrage) {
    // ----------- << method.body@AAAAAAGEIHt5eyFqOnk= >>
    // ----------- >>
    }
    /**
    * @param l Lettrine 
    * @param t Tag
    */

    // ----------- << method.annotations@AAAAAAGEIHvxLSTVufQ= >>
    // ----------- >>
    public void tager(void l Lettrine, void t Tag) {
    // ----------- << method.body@AAAAAAGEIHvxLSTVufQ= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGEEKm5d/fG0Tk= >>
// ----------- >>
}