/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Whole;


// ----------- << imports@AAAAAAGEEKmRc/dy6X0= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEEKmRc/dy6X0= >>
// ----------- >>
public class TagDAO extends AbstractDAO {
// ----------- << class.extras@AAAAAAGEEKmRc/dy6X0= >>
// ----------- >>
}